networks:
  custom_network:
    driver: bridge

services:
  webmethods:
    image: digitalfindmore/demo_api_msr:1.0
    container_name: msr_container
    networks:
      - custom_network 
    ports:
      - 5555:5555
    depends_on:
      mysql:
        condition: service_healthy

  mysql:  
    image: digitalfindmore/demo_api_mysql:1.0 
    container_name: mysql_container
    networks:
      - custom_network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TABLE: ${MYSQL_TABLE}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${MYSQL_USER} -p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 5
